name: test
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runtime:
          - deno
          - node
          - wasmer
          - wasmtime

    runs-on: ubuntu-latest
    steps:
      - name: Clone tests
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-test-suite
          path: tests

      - name: Clone tools
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-test-tools
          path: tools

      - name: Setup deno
        if: matrix.runtime == 'deno'
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Setup wasmer
        if: matrix.runtime == 'wasmer'
        run: |-
          curl https://get.wasmer.io -sSfL | sh
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Setup wasmtime
        if: matrix.runtime == 'wasmtime'
        run: |-
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Run tests
        shell: python
        run: |-
          import glob
          import json
          import subprocess
          import sys
          import os

          command = os.path.abspath("tools/run-${{ matrix.runtime }}")
          version_output = subprocess.check_output([command, "-V"])
          version_output = version_output.decode("utf-8")
          version_output = version_output.rstrip("\n")

          (runtime_name, runtime_version) = tuple(version_output.split(" "))

          results = []
          for path in glob.glob("tests/*/*.wasm"):
              process = subprocess.run(["tools/wasm-test", command, path],
                      capture_output=True, text=True)

              path = os.path.relpath(path, os.path.join(os.curdir, "tests"))

              status = None
              if process.returncode == 0:
                  status = "PASS"
              else:
                  status = "FAIL"

              message = process.stdout

              results.append({
                'path': path,
                'status': status,
                'message': message,
              })

          data = {
            'runtime': {
                'name': runtime_name,
                'version': runtime_version,
            },
            'results': results,
          }

          sha = subprocess.check_output(['git', '-C', 'tests', 'rev-parse', 'HEAD'])
          sha = str(sha, "utf-8").strip()

          path = os.path.join(sha, runtime_name, runtime_version + '.json')
          os.makedirs(os.path.dirname(path), exist_ok=True)

          with open(path, 'w', encoding='utf-8') as file:
            json.dump(data, file, ensure_ascii=False, indent=4)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: "**/*.json"

  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: test

      - name: Commit artifact
        run: |-
          git config user.name "Casper Beyer"
          git config user.email "caspervonb@pm.me"
          git add -A .
          git commit -m "Run $(date)"
          git push